### ISSUE TITLE
TPC-C Java implementation review

### ISSUE THREAD

**Issue by aklenik** [ftsrg/blockchain-benchmarks-tpcc#15]
- [x] Make the intended usage of transaction functions explicit at places like these (and put the annotation directly before the function signature, not before the comment):
    https://github.com/ftsrg/blockchain-benchmarks-tpcc/blob/07bffd3b29a0a4e31e4a177e818e16dad91c92be/smart-contract/hyperledger-fabric/v2/java/src/main/java/hu/bme/mit/ftsrg/tpcc/TPCC.java#L63-L71
- [x] Fix missing `skipped` and `deliveredOrders` issue:
    https://github.com/ftsrg/blockchain-benchmarks-tpcc/blob/07bffd3b29a0a4e31e4a177e818e16dad91c92be/smart-contract/hyperledger-fabric/v2/java/src/main/java/hu/bme/mit/ftsrg/tpcc/TPCC.java#L82-L84
- [ ] #16

**Comment by KangogoDamarisKE** [comment]
fixed the above first and second issues.

**Comment by bzp99** [comment]
@aklenik the code has been significantly altered (transactions have been broken up to multiple method calls, reference comments to the TPC-C spec have been made more verbose, etc) since the opening of this PR; just a heads up :)

**Comment by aklenik** [comment]
@bzp99 I'll open a new issue for the new code-base.
