### ISSUE TITLE
Reorganize the package structure of the Java implementation

### ISSUE THREAD

**Issue by aklenik** [ftsrg/blockchain-benchmarks-tpcc#6]
Something like the following structure is desirable:
```
src/main/java/hu/bme/mit/ftsrg/
├─ entries/
│  ├─ Customer.java
│  ├─ ...
├─ inputs/
│  ├─ DeliveryInput.java
│  ├─ ...
├─ outputs/
│  ├─ DeliveryOutput.java
│  ├─ ...
├─ utils/
│  ├─ Common.java
├─ TPCC.java
```

Meaning:
- [x] The root package should be `hu.bme.mit.ftsrg` to reflect the correct organizational structure as per Java package naming conventions.
- [x] The classes should be separated according to their purpose (entries, inputs, outputs, utils), and their packages updated accordingly.
- [x] ~Cammel~ Pascal casing should be used for all source files (`common.java` -> `Common.java` or `Utils.java`).
- [x] `*Input.java` and `*Output.java` should be used to denote the parameters and return values, respectively, of the transaction profile functions.

**Comment by bzp99** [comment]
Partially resolved by c2dca34, but @KangogoDamarisKE  please fix the package names from `hu.bme.mit.ftsrc` to `hu.bme.mit.ftsrg`. Also, please verify that every subtask (checkbox) in Attila’s OP has been handled and if so, tick them.

**Comment by bzp99** [comment]
One more thing: the metadata in `build.gradle.kts` should also be updated to reflect the new group name

- [ ] Done

**Comment by bzp99** [comment]
@aklenik please check if the recent changes to `dev-java` indeed resolve this problem and if so, we can close this

**Comment by aklenik** [comment]
Looks okay for now, so I'm closing this issue.
